
<div class="container mt-3">
    <h1>Cadastro</h1>
    <form enctype="multipart/form-data" method="post" action="">
        <label for="name">Nome:</label>
        <input name="name" type="text" class="form-control" id="name">
        <br>
        <label for="price">Preço:</label>
        <input name="price" type="number" class="form-control" id="price">
        <br>
        <label for="quantity">Quantidade:</label>
        <input name="quantity" type="number" class="form-control" id="quantity">
        <br>
        <label for="description">Descrição:</label>
        <textarea name="description" type="text" class="form-control" id="description"></textarea>
        <br>
        <label for="photo">Fotos:</label>
        <input name="photo" type="file" class="form-control" id="photo">
        <br>
        <button class="btn btn-danger">Enviar</button>
    </form>
</div>
