<style>
    img {
        width: 30%;
    }
    tr {

    }
</style>
<div class="container mt-03">
    <table class="table table-striped table-hover">
        <h1>Listagem</h1>
        <thead>
            <tr class="table-dark text-center">
                <td>Nome</td>
                <td>Preço</td>
                <td>Quantidade</td>
                <td>Descrição</td>
                <td>Foto</td>
                <td>Ações</td>
            </tr>
        </thead>
        <tbody>
        <?php
            foreach ($data as $id =>  $row){
                $product = explode(';',$row);
                echo "<tr class='text-center'>
                        <td>{$product[0]}</td>
                        <td>{$product[1]}</td>
                        <td>{$product[2]}</td>
                        <td>{$product[3]}</td>
                        <td><img src='{$product[4]}'</td>
                        <td>
                            <a href='/editar?id={$id}' class='btn btn-primary'>Editar</a>
                            <a href='/excluir?id={$id}' class='btn btn-danger'>Excluir</a>
                        </td>
                      </tr>";
            }
        ?>
        </tbody>

    </table>
</div>