<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

<meta charset="pr-br">

    <div class="container mt-3">
        <a class="btn btn-danger" href="/">Inicio</a>
        <a class="btn btn-danger" href="/cadastro" >Cadastro</a>
        <a class="btn btn-danger" href="/listar">Listar</a>
        <hr>
    </div>
