<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <title>Veículos</title>
        <meta charset="utf-8">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    </head>
    <body class="container">
        <div class="mt-5">
            <h1>Meus Veículos</h1>
            <hr>
            <a class="btn btn-info" href="/veiculos/listar">Listar</a>
            <a class="btn btn-info" href="/veiculos/adicionar">Adicionar</a>

        </div>
        <div class="card card-body mt-5">
            <?php main(); ?>
        </div>
    </body>
</html>