<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

<div class="container mt-5">
    <form action="" method="post">
        <label>Nome</label>
        <input for="name" type="text" class="form-control">
        <br>

        <label>Email</label>
        <input for="email" type="email" class="form-control">
        <br>

        <label>Telefone</label>
        <input for="telefone" type="number" class="form-control">
        <br>
        <button class="btn btn-primary">Enviar</button>
    </form>
</div>