<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
<link rel="stylesheet" href="./css/style.css">
<div class="container mt-5">
        <h1>Contatinhos</h1>
        <a class="btn btn-primary" href="/cadastrar">Novo Contato</a>
        <a class="btn btn-primary" href="/listar">Lista Contato</a>
    <hr>
</div>