<!--<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
-->
<div class="container mt-5">
    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <th>Nome</th>
            <th>Email</th>
            <th>Telefone</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        <?php
            foreach ($contatinhos as $linha){
                $contato = explode(';', $linha);
                echo "<tr>
                    <td>{$contato[0]}</td>
                    <td>{$contato[1]}</td>
                    <td>{$contato[2]}</td>
                   </tr>
                    ";
            }
        ?>
        </tbody>
    </table>
</div>