<div class="container mt-5">
    <form action="" method="post">
        <label>Nome:</label>
        <input name="name" type="text" class="form-control">
        <br>
        <label>E-mail:</label>
        <input name="email" type="email" class="form-control">
        <br>
        <label>Telefone:</label>
        <input name="number" type="number" class="form-control">
        <br>
        <button class="btn btn-danger">Enviar</button>
    </form>
</div>