<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

<div class="container mt-5">
    <h1>Contatinhos</h1>
    <br>
    <a href="/cadastro" class="btn btn-danger">Novo Contato</a>
    <a href="/listar" class="btn btn-danger">Listar Contato</a>
    <hr>
</div>
