<div class="container mt-5">
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Nome</th>
                <th>E-mail</th>
                <th>Telefone</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
        <?php
            foreach ($contatinhos as $linha){
                $contato = explode(';',$linha);
                echo "<tr>
                    <td>{$contato[0]}</td>
                    <td>{$contato[1]}</td>
                    <td>{$contato[2]}</td>
                </tr>
                ";
            }

        ?>
        </tbody>
    </table>
</div>


