<!--<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">-->


<div class="container mt-3">
    <h1>Cadastro de Produtos</h1>
    <form enctype="multipart/form-data" action="" method="post">
        <label for="name">Nome:</label>
        <input name="name" type="text" class="form-control" id="name">
        <br>
        <label>Preço:</label>
        <input name="price" type="text" class="form-control" id="price">
        <br>
        <label>Quantidade:</label>
        <input name="quantity" type="text" class="form-control" id="quantity">
        <br>
        <label>Descrição:</label>
        <textarea name="description" type="text" class="form-control" id="description"></textarea>
        <br>
        <label>Foto</label>
        <input name="photo" type="file" class="form-control" id="photo">
        <br>
        <button class="btn btn-danger">Enviar</button>
    </form>

</div>