<style>
    img {
        width: 20%;
    }
</style>
<div class="container mt-3">
    <h1>Listagem de Produtos</h1>
    <table class="table table-striped table-hover">
        <thead>
        <tr class="table-dark text-center">
            <th>Nome</th>
            <th>Preço</th>
            <th>Quantidade</th>
            <th>Descrição</th>
            <th>Foto</th>
            <th>Ações</th>
        </tr>
        </thead>
        <tbody class="text-center">
        <?php
        foreach ($data as $id => $row){
            $product = explode(';', $row);
            echo "<tr class='text-center'>
                    <td>{$product[0]}</td>
                    <td>{$product[1]}</td>
                    <td>{$product[2]}</td>
                    <td>{$product[3]}</td>
                    <td><img src='{$product[4]}'</td>
                    <td>
                        <a href='/editar?id={$id}'' class='btn btn-outline-primary'>Editar</a>
                        <a href='/excluir?id={$id}' class='btn btn-outline-danger'>Excluir</a>
                        </td>
                   </tr>
                    ";
        }
        ?>
        </tbody>
    </table>
</div>



