<!---->
<!--<div class="container mt-3">-->
<!--    <h1>Cadastro de Produtos</h1>-->
    <form action="" method="post">
        <label for="make">Nome:</label>
        <input name="make" type="text" required class="form-control" id="make">
        <br>
        <label for="model">Modelo</label>
        <input name="model" type="text" required class="form-control" id="model">
        <br>
        <label for="year">Ano</label>
        <input name="year" type="text" required class="form-control" id="year">
        <br>
        <label for="mileage">KM</label>
        <input name="mileage" type="text" required class="form-control" id="mileage">
        <br>
        <label for="plate">Placa</label>
        <input name="plate" type="text" required class="form-control" id="plate">
        <br>
        <button class="btn btn-danger">Enviar</button>
    </form>

<!--</div>-->