<!--<div class="container mt-3">-->
<!--    <h1>Listagem de Produtos</h1>-->
    <table class="table table-striped table-hover">
        <thead>
        <tr class="table-info text-center">
            <th>Marca</th>
            <th>Modelo</th>
            <th>Ano</th>
            <th>Km</th>
            <th>Placa</th>
            <th>Ações</th>
        </tr>
        </thead>
        <tbody class="text-center">
        <?php
            foreach ($vehicles as $vehicle) {
                echo "
                <th>Marca</th>
                <th>Modelo</th>
                <th>Ano</th>
                <th>Km</th>
                <th>Placa</th>
                <th>...</th>       
                ";
            }
        ?>
        </tbody>
    </table>
<!--</div>-->